name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: my-thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: my-thesis.aux
          compiler: bibtex
          args: 
      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          root_file: my-thesis.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: my-thesis.pdf
          name: $(date "+%Y%m%d")
